"""make roles global

Revision ID: ad6dd933acd2
Revises: d5bd51a698c9
Create Date: 2026-09-24 21:47:39.613768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad6dd933acd2'
down_revision: Union[str, Sequence[str], None] = 'd5bd51a698c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'restaurant_id', schema='prime_auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('restaurant_id', sa.UUID(), autoincrement=False, nullable=False), schema='prime_auth')
    # ### end Alembic commands ###
